os: linux
sudo: false
language: python
python:
  - 3.6
  - 3.5
  - 3.4
  - 2.7
  - nightly
  - pypy3
env: TOXENV=py,coveralls

matrix:
  include:
    - env: TOXENV=docs-html
  allow_failures:
    - python: nightly
    - python: pypy3
  fast_finish: true

install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install ipaddress; fi
  - pip install tox

script:
  - tox

cache:
  - pip

branches:
  only:
    - master
    - /^.*-maintenance$/

notifications:
  email: false
