language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - pypy
env:
  global:
    - DATEUTIL=python-dateutil==2.1
    - LOCALFLAVOR=
  matrix:
    - DJANGO=Django==1.4.10
    - DJANGO=Django==1.5.4 DATEUTIL=python-dateutil==2.2
    - DJANGO=Django==1.5.5 LOCALFLAVOR=django-localflavor
    - DJANGO=Django==1.6 LOCALFLAVOR=django-localflavor

matrix:
  exclude:
    - python: 3.3
      env: DJANGO=Django==1.4.10

# command to install dependencies
install:
  - "pip install $DJANGO $DATEUTIL $LOCALFLAVOR --use-mirrors"
  - "pip install . --use-mirrors"
  - "pip install -r tests/test_requirements.txt --use-mirrors"

# command to run tests
script: "coverage run tests/runtests.py --with-pep8 --force-all"
after_success:
  - pip install coveralls
  - coveralls
