---
os: linux
language: python

python:
  - '3.8'
  - '3.7'
  - '3.6'
  - '3.5'
  - pypy3

env:
  - TOXENV=py

matrix:
  include:
    - python: '2.7'
      env: TOXENV=py27

install:
  - pip install tox

script:
  - tox

after_success:
  - pip install coveralls
  - coverage report
  - coveralls

cache:
  - pip

branches:
  only:
    - master
    - /^.*\.x$/

notifications:
  email: false
