language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - pypy
env:
  global:
    - SQLALCHEMY=SQLAlchemy==0.8.5
    - DATEUTIL=python-dateutil==2.1
    - LOCALFLAVOR=
  matrix:
    - DJANGO="Django<1.5"
    - DJANGO=Django==1.5.4 DATEUTIL=python-dateutil==2.2 SQLALCHEMY=SQLAlchemy==0.9.3
    - DJANGO=Django==1.5.5 LOCALFLAVOR=django-localflavor SQLALCHEMY=SQLAlchemy==0.7.10
    - DJANGO="Django<1.7" LOCALFLAVOR=django-localflavor

matrix:
  exclude:
    - python: 3.3
      env: DJANGO="Django<1.5"

install:
  - "pip install $DJANGO $DATEUTIL $LOCALFLAVOR $SQLALCHEMY -r tests/test_requirements.txt"

script: "coverage run tests/runtests.py --with-pep8 --force-all"
after_success:
  - pip install coveralls
  - coveralls
