---
os: linux
dist: xenial
language: python

python:
  - '3.8'
  - '3.7'
  - '3.6'
  - pypy3

env: TOXENV=py,coverage-ci

matrix:
  include:
    - env: TOXENV=style
    - env: TOXENV=docs

install:
  - pip install tox

script:
  - tox

cache:
  - pip

branches:
  only:
    - master
    - /^.*\.x$/

notifications:
  email: false
