---
os: linux
dist: xenial
language: python

python:
  - 3.8
  - 3.7
  - 3.6
  - 3.5
  - nightly
  - pypy3
env: TOXENV=py,coveralls

jobs:
  include:
    - python: "3.8"
      env: TOXENV=py38,stylecheck,docs-html,coveralls
  allow_failures:
    - python: nightly
    - python: pypy3
  fast_finish: true

install:
  - pip install tox

script:
  - tox

cache:
  - pip

branches:
  only:
    - master
    - /^.*-maintenance$/

notifications:
  email: false
