language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
# command to install dependencies
install:
  - "pip install . --use-mirrors"
  - "pip install -r tests/test_requirements.txt --use-mirrors"
  - "if [ ${TRAVIS_PYTHON_VERSION:0:1} != 3 ]; then pip install Babel --use-mirrors; fi"
# command to run tests
script: coverage run --source=wtforms tests/runtests.py --with-pep8
after_success:
  - coveralls
